spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://47.103.200.57:3306/backend?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  rabbitmq:
    host: 47.103.200.57
    port: 5672
    username: tmy
    password: 123456
    virtual-host: /backend
  redis:
    host: 47.103.200.57
    port: 6379
    password: tmy001117
    database: 0
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
server:
  port: 80
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/resources/mapper/*.xml
  global-config:
    db-config:
      capital-mode: true
logging:
  config: classpath:logback-spring.xml
