spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backend?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
server:
  port: 80
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/resources/mapper/*.xml
  global-config:
    db-config:
      capital-mode: true
logging:
  config: classpath:logback-spring.xml