spring:
  datasource:
    url: jdbc:mysql://47.103.200.57:3306/backend?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080